### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by AlexeiWaterFire** [Nsity/eschool#5]
Всем доброго времени суток, при попытке входа, где вводится логин и пароль выдаёт ошибку 404. В интернете многое читал, но ничего не помогло. По прошлым комментариям на самой работе файлы исправили, но я всё-же не могу исправить ошибку.
Прошу помочь!
![Снимок](https://user-images.githubusercontent.com/67323552/171047170-14cdf6b3-411e-484b-9dc0-928baf196dd7.PNG)

**Comment by nerschossen** [comment]
получилось?
